site_name: PHYS281
site_url: https://ma.ttpitk.in/teaching/PHYS281
site_author: Matthew Pitkin

theme:
  name: material

  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: 'index.md'
  - Course notes:
    - Getting started:
       - Installing and using Anaconda: 'demo-anaconda.md'
       - Installing and using VS code: 'demo-vs-code.md'
       - Using a terminal: 'demo-terminal.md'
       - The Python terminal: 'demo-python-terminal.md'
       - Quick Start Guide: 'demo-quickstart.md'
    - Introduction to Python:
       - Basic data types: 'demo-data-types.md'
       - Compound data types: 'demo-compound-data-types.md'
       - Built-in functions: 'demo-built-in-functions.md'
       - Python scripts: 'demo-scripts.md'
       - Importing modules: 'demo-importing-modules.md'
       - Flow control: 'demo-flow-control.md'
       - Python functions: 'demo-functions.md'
       - Python classes: 'demo-classes.md'
       - Reading and writing data: 'demo-io.md'
       - Error checking and debugging: 'demo-error-checking.md'
       - NumPy basics: 'demo-numpy.md' 
       - Basic plotting with Matplotlib: 'demo-matplotlib.md'
       - Code testing: 'demo-unit-tests.md'
    - Numerical methods:
       - Numerical integration: 'numerical-integration.md'
       - Fitting a line: 'demo-line-fitting.md'
    - Course project:
       - Gravity simulation: 'gravity.md'
       - Marking criteria: 'markinggrid.md'
    - Exercises: 'exercises.md'
    - glossary.md

docs_dir: 'docs'

extra_css:
  - css/asciinema-player.css
  - css/tooltips.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/configs.js
  - javascripts/asciinema-player.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6
  - javascripts/glossary.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mdtooltipslink:
      js_file: docs/javascripts/glossary.js
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
